config/routes.rb
Rails.application.routes.draw do

  resources :posts
  get 'posts/:id/delete' => 'posts#delete', :as => :posts_delete

  devise_for :users
  
  root "pages#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts

  def admin?
  	self.admin == true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
   def require_admin
  	redirect_to '/posts' unless current_user.admin?
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index
		if user_signed_in?
			redirect_to('/posts')
		end
	end

	def redirect
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_admin, only: [ :edit, :update, :delete, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to(:action => 'index')
    else
      render('new')
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to(:action => 'show', :id => @post.id)
    else
      render('index')
    end
  end

  def delete
    @post = Post.find(params[:id])
  end

  def destroy
    Post.find(params[:id]).destroy
    redirect_to(:action => 'index')
  end

private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/user/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/user/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rails Test Project</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<div class="container">
	<div class="login-container">
		<h4 style="margin:0 0 5px 0;">Welcome to my Rails Test Project</h4>
		<p>Please login or register below:</p>
		<div class="clearfix">
			<div style="display: inline-block;"><%= button_to "Login", new_user_session_path, method: "get" %></div>
			<div style="display: inline-block; margin-left:10px;"><%= button_to "Register", new_user_registration_path, method: "get" %></div>
		</div>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for (@post) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %><br>
    <%= f.label :content, "Content (HTML Friendly)" %>
    <%= f.text_area :content, size: "24x6" %><br>

  <div class='actions'>
    <%= f.submit %>
    <%= button_to 'Back', posts_path, method: "get" %>
  </div>
 <% end %>

app/views/posts/delete.html.erb
<div class="container">
	<div class="post-container">	
		<div class="clearfix row">
			<div class="post">
				<p class="title"><%= @post.title %></p>
				<p class="author"><%= mail_to @post.user.email %></p>
				<p class="content"><%= raw @post.content %></p>

				<div class="warning">
					<p>Are you sure you want to delete this post?</p>
					<%= link_to 'Delete', @post, :confirm => "Delete", :method => :delete %>
					<%= link_to 'Edit', edit_post_path(@post) %>	
					<%= link_to 'Back', posts_path %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/posts/edit.html.erb
<div class="container">
	<div class="post-container">	
		<div class="clearfix row">
			<h3>Edit Post</h3>
			<div class="post">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/posts/index.html.erb
<div class="container">
	<div class="header">
		<div style="display: inline-block;"><%= button_to 'New Post', new_post_path, method: "get" %></div>
		<div style="display: inline-block; margin-left:10px;"><%= button_to 'Logout', destroy_user_session_path, method: "delete" %></div>
	</div>
	<div class="post-container">	
		<% @posts.in_groups_of(3).each do |posts| %>
			<% posts.select! {|x| !x.nil?} %>
			<div class="clearfix row">
				<% posts.each do |post| %>
					<div class="post">
						<p class="title"><%= post.title %></p>
						<p class="author"><%= mail_to post.user.email %></p>
						<p class="content"><%= raw post.content %></p>
						<%= link_to 'View', post %>
						<% if current_user.admin? %>
							<%= link_to 'Edit', edit_post_path(post) %>
							<%= link_to 'Delete', posts_delete_path(post) %>
						<% end %>
					</div>
				<% end %>
			</div>
		<% end %>
	</div>
</div>

app/views/posts/new.html.erb
<div class="container">
	<div class="post-container">	
		<div class="clearfix row">
			<h3>New Post</h3>
			<div class="post">
				<%= render 'form' %>
			</div>
		</div>
	</div>
</div>

app/views/posts/show.html.erb
<div class="container">
	<div class="post-container">	
		<div class="clearfix row">
			<div class="post">
				<p class="title"><%= @post.title %></p>
				<p class="author"><%= mail_to @post.user.email %></p>
				<p class="content"><%= raw @post.content %></p>
				<%= link_to 'Back', posts_path %>
				<%= link_to 'Edit', edit_post_path(@post) %>
				<%= link_to 'Delete', posts_delete_path(@post) %>
			</div>
		</div>
	</div>
</div>